version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ".env"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:ggfdsgsdf234gds123@postgres:5432/postgres
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=2048
    # Add memory limit for the container
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ggfdsgsdf234gds123
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

  jobs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:ggfdsgsdf234gds123@postgres:5432/postgres
      - NODE_ENV=production
    command: bun run jobs:start
    # Memory limits for jobs service
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  postgres_data:
